version = 0.1

[qa.deploy.parameters]
stack_name = "alloy-evaluation-function"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bcwtryyiha3k"
s3_prefix = "alloy-evaluation-function"
confirm_changeset = true

[prod.deploy.parameters]
stack_name = "alloy-evaluation-function"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mtc2hi8v8bsc"
s3_prefix = "alloy-evaluation-function"
confirm_changeset = true
