resources:
- name: docker-image-ubuntu
  type: docker-image
  source:
    repository: ubuntu
    tag: 20.04
- name: git-repo
  type: git
  source:
    uri: ((github_uri))
    branch: ((github_branch))
    access_token: ((github_access_token))

jobs:
  - name: build
    plan:
      - get: docker-image-ubuntu
        trigger: true
      - get: git-repo
        trigger: true
      - task: build
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
            - name: workspace
          inputs:
            - name: git-repo
          params:
            s3_bucket_name: ((s3_bucket_name))
            AWS_REGION_PROD: ((AWS_REGION_PROD))
            AWS_ACCESS_KEY_ID_PROD: ((AWS_ACCESS_KEY_ID_PROD))
            AWS_SECRET_ACCESS_KEY_PROD: ((AWS_SECRET_ACCESS_KEY_PROD))
          run:
            path: /bin/bash
            args: ["git-repo/.pipeline/scripts/build.sh"]
    
  - name: deploy-dev
    plan:
      - get: docker-image-ubuntu
        trigger: true
      - task: deploy-dev
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
            - name: workspace
          inputs:
            - name: git-repo
          params:
            s3_bucket_name: ((s3_bucket_name))
            AWS_REGION_DEV: ((AWS_REGION_DEV))
            AWS_ACCESS_KEY_ID_DEV: ((AWS_ACCESS_KEY_ID_DEV))
            AWS_SECRET_ACCESS_KEY_DEV: ((AWS_SECRET_ACCESS_KEY_DEV))
            AWS_SESSION_TOKEN_DEV: ((AWS_SESSION_TOKEN_DEV))
            AWS_PAGER: ((AWS_PAGER))
          run:
            path: /bin/sh
            args: ["git-repo/.pipeline/scripts/deploy_dev.sh"]

  - name: unit-test
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [build]
      - task: unit-test
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              sleep 10
              echo "Running unit test..."
  - name: deploy-test
    plan:
      - get: docker-image-ubuntu
        trigger: false
        passed: [deploy-dev]
      - task: deploy-test
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting deploy to test..."
    serial: true
  - name: integration-test
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [deploy-test]
      - task: integration-test
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Running integration test..."
  - name: load-test
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [deploy-test]
      - task: load-test
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Running load test..."
  - name: deploy-prod
    plan:
      - get: docker-image-ubuntu
        trigger: false
        passed: [integration-test, load-test]
      - task: deploy-prod
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting deploy to prod..."