resources:
- name: docker-image-ubuntu
  type: docker-image
  source:
    repository: ubuntu
    tag: 20.04
jobs:
  - name: build
    plan:
      - get: docker-image-ubuntu
        trigger: true
      - task: concourse-poc
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          inputs:
          - name: git-repo
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting build..."
  - name: deploy-dev
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [build]
      - task: concourse-poc
        image: docker-image-ubuntu
        config:
          platform: linux
          outputs:
          - name: workspace
          inputs:
          - name: git-repo
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting deploy to dev..."
  - name: deploy-test
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [deploy-dev]
      - task: concourse-poc
        config:
          platform: linux
          image: docker-image-ubuntu
          outputs:
          - name: workspace
          inputs:
          - name: git-repo
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting deploy to test..."
  - name: deploy-prod
    plan:
      - get: docker-image-ubuntu
        trigger: true
        passed: [deploy-test]
      - task: concourse-poc
        config:
          platform: linux
          image: docker-image-ubuntu
          outputs:
          - name: workspace
          inputs:
          - name: git-repo
          run:
            path: /bin/sh
            args:
            - -c
            - |
              output_dir=workspace
              echo "Starting deploy to prod..."