version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-python-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ssa74km4w6q0"
s3_prefix = "dev-python-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
