version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ssa74km4w6q0"
s3_prefix = "python-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
